# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KiliaroTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KiliaroTest

  pod 'JamitFoundation', :git => 'https://github.com/JamitLabs/JamitFoundation.git', :tag => '1.5.2', :inhibit_warnings => true
  pod 'Alamofire'
  pod 'Swinject'

  target 'KiliaroTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KiliaroTestUITests' do
    # Pods for testing
  end

end
